In [2]:
from MultiLayerPerceptron import *

In [3]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris

In [4]:
xin = np.array([1, 0, 0])
win = np.array([0.716, 0.742, 0.576])
n1 = neural_neuron(w_in=win, layer="hidden", pos=1)
n1.feedforward(x_in=xin)
print(n1.z)

0.671725582405139


In [5]:
print(sigmoid_act(x=0.716, derivate=False))

0.671725582405139


In [6]:
win_layer = np.array([[0.716, -0.536, -0.590],
                      [0.742, -0.262, 0.170],
                      [0.576, 0.872, 0.034]])
xin_layer = np.array([1, 0, 0])
l1 = neural_layer(w_in=win_layer, bias=1 ,n_neurons=3, pos="hidden")
l1.feedforward(x_in=xin_layer)
print(l1.neurons[0].w)
print(l1.neurons[0].pos)
print(l1.y)

[0.716 0.742 0.576]
1
[1.         0.67172558 0.36911857 0.35663485]


In [7]:
xin_layer_input = np.array([0, 0])

win_layer_hidden = np.array([[0.716, -0.536, -0.590],
                             [0.742, -0.262, 0.170],
                             [0.576, 0.872, 0.034]])

win_layer_output = np.array([[-0.754],
                             [-0.590],
                             [0.564],
                             [0.744]])

In [8]:
layer_input = neural_layer(bias=1, n_neurons=2, pos="input")
layer_input.feedforward(x_in=xin_layer_input)
print(layer_input.y)

layer_hidden = neural_layer(w_in=win_layer_hidden, bias=1, n_neurons=3, pos="hidden")
layer_hidden.feedforward(x_in=layer_input.y)
print(layer_hidden.y)

layer_output = neural_layer(w_in=win_layer_output, n_neurons=1, pos="output")
layer_output.feedforward(x_in=layer_hidden.y)
print(layer_output.y)

[1. 0. 0.]
[1.         0.67172558 0.36911857 0.35663485]
[0.33697613]


In [9]:
ann = neural_network(layer_input_neurons=2, layer_hidden_neurons=3, layer_output_neurons=1)

print(ann.w_hidden)
print()
print(ann.w_output)
print("------------------------------------------------")

ann.feedforward(x_in=np.array([0, 0]))
ann.error(target=np.array([0]))
print(ann.layer_input.y)
print()
print(ann.layer_hidden.y)
print()
print(ann.layer_output.y)
print()
print(ann.error_v)
print(ann.error_epoch)

[[-0.59848846  0.96845033  0.65804015]
 [-0.31010872  0.00662623  0.23026751]
 [ 0.84118134 -0.78732769  0.48385924]]

[[ 0.47802969]
 [-0.91972455]
 [ 0.7868733 ]
 [-0.47926931]]
------------------------------------------------
[1. 0. 0.]

[1.         0.35468959 0.72481051 0.65882   ]

[0.6002231]

[0.36026777]
0.3602677742481062
