In [11]:
from MultiLayerPerceptron import *

In [12]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris

In [13]:
xin = np.array([1, 0, 0])
win = np.array([0.716, 0.742, 0.576])
n1 = neural_neuron(w_in=win, layer="hidden", pos=1)
n1.feedforward(x_in=xin)
print(n1.z)

0.671725582405139


In [14]:
print(sigmoid_act(x=0.716, derivate=False))

0.671725582405139


In [15]:
win_layer = np.array([[0.716, -0.536, -0.590],
                      [0.742, -0.262, 0.170],
                      [0.576, 0.872, 0.034]])
xin_layer = np.array([1, 0, 0])
l1 = neural_layer(w_in=win_layer, bias=1 ,n_neurons=3, pos="hidden")
l1.feedforward(x_in=xin_layer)
print(l1.neurons[0].w)
print(l1.neurons[0].pos)
print(l1.y)

[0.716 0.742 0.576]
1
[1.         0.67172558 0.36911857 0.35663485]


In [16]:
xin_layer_input = np.array([0, 0])

win_layer_hidden = np.array([[0.716, -0.536, -0.590],
                             [0.742, -0.262, 0.170],
                             [0.576, 0.872, 0.034]])

win_layer_output = np.array([[-0.754],
                             [-0.590],
                             [0.564],
                             [0.744]])

In [17]:
layer_input = neural_layer(bias=1, n_neurons=2, pos="input")
layer_input.feedforward(x_in=xin_layer_input)
print(layer_input.y)

layer_hidden = neural_layer(w_in=win_layer_hidden, bias=1, n_neurons=3, pos="hidden")
layer_hidden.feedforward(x_in=layer_input.y)
print(layer_hidden.y)

layer_output = neural_layer(w_in=win_layer_output, n_neurons=1, pos="output")
layer_output.feedforward(x_in=layer_hidden.y)
print(layer_output.y)

[1. 0. 0.]
[1.         0.67172558 0.36911857 0.35663485]
[0.33697613]


In [18]:
ann = neural_network(layer_input_neurons=2, layer_hidden_neurons=3, layer_output_neurons=1)

print("Pesos (hidden):")
print(ann.w_hidden)
print()
print("Pesos (output):")
print(ann.w_output)

print("------------------------------------------------")

ann.feedforward(x_in=np.array([0, 0]))
ann.error(target=np.array([0]))
print("Salida (input):")
print(ann.layer_input.y)
print()
print("Salida (hidden):")
print(ann.layer_hidden.y)
print()
print("Salida (output):")
print(ann.layer_output.y)
print()

Pesos (hidden):
[[-0.25137152 -0.61876951  0.10739667]
 [-0.66807284  0.19119718  0.72773937]
 [-0.64557546 -0.75834438 -0.24210596]]

Pesos (output):
[[ 0.0343381 ]
 [-0.10685133]
 [ 0.7576162 ]
 [ 0.48201375]]
------------------------------------------------
Salida (input):
[1. 0. 0.]

Salida (hidden):
[1.         0.43748595 0.35006136 0.52682339]

Salida (output):
[0.62404204]



In [19]:
ann.backpropagation()

print("Delta (output):")
print(ann.layer_output.d)
print()
print("Delta pesos (output):")
print(ann.layer_output.d_w)
print()

print("------------------------------------------------")
print()

print("Delta (hidden):")
print(ann.layer_hidden.d_in)
print()
print("Delta pesos (hidden):")
print(ann.layer_hidden.d_w)
print()

Delta (output):
[-0.14175584]

Delta pesos (output):
[[-0.04252675]
 [-0.01860486]
 [-0.01488697]
 [-0.02240409]]

------------------------------------------------

Delta (hidden):
[[-0.00486763]
 [ 0.0151468 ]
 [-0.10739652]
 [-0.06832827]]

Delta pesos (hidden):
[[-0.00028711]
 [ 0.00108334]
 [-0.00781293]
 [-0.00478487]]



In [20]:
print("Pesos (hidden):")
print(ann.layer_hidden.w)
print()
print("Pesos (output):")
print(ann.layer_output.w)
print()

ann.update_weights()
print("------------------------------------------------")
print()

print("Pesos updated (hidden):")
print(ann.layer_hidden.w)
print()
print("Pesos updated (output):")
print(ann.layer_output.w)
print()

Pesos (hidden):
[[-0.25137152 -0.61876951  0.10739667]
 [-0.66807284  0.19119718  0.72773937]
 [-0.64557546 -0.75834438 -0.24210596]]

Pesos (output):
[[ 0.0343381 ]
 [-0.10685133]
 [ 0.7576162 ]
 [ 0.48201375]]

------------------------------------------------

Pesos updated (hidden):
[[-0.25137152 -0.61876951  0.10739667]
 [-0.66807284  0.19119718  0.72773937]
 [-0.64557546 -0.75834438 -0.24210596]]

Pesos updated (output):
[[-0.00818866]
 [-0.12545619]
 [ 0.74272923]
 [ 0.45960966]]

