In [69]:
from MultiLayerPerceptron import *

In [70]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris

In [71]:
xin = np.array([1, 0, 0])
win = np.array([0.716, 0.742, 0.576])
n1 = neural_neuron(w_in=win, layer="hidden", pos=1)
n1.feedforward(x_in=xin)
print(n1.z)

0.671725582405139


In [72]:
print(sigmoid_act(x=0.716, derivate=False))

0.671725582405139


In [73]:
win_layer = np.array([[0.716, -0.536, -0.590],
                      [0.742, -0.262, 0.170],
                      [0.576, 0.872, 0.034]])
xin_layer = np.array([1, 0, 0])
l1 = neural_layer(w_in=win_layer, bias=1 ,n_neurons=3, pos="hidden")
l1.feedforward(x_in=xin_layer)
print(l1.neurons[0].w)
print(l1.neurons[0].pos)
print(l1.y)

[0.716 0.742 0.576]
1
[1.         0.67172558 0.36911857 0.35663485]


In [74]:
xin_layer_input = np.array([0, 0])

win_layer_hidden = np.array([[0.716, -0.536, -0.590],
                             [0.742, -0.262, 0.170],
                             [0.576, 0.872, 0.034]])

win_layer_output = np.array([[-0.754],
                             [-0.590],
                             [0.564],
                             [0.744]])

In [75]:
layer_input = neural_layer(bias=1, n_neurons=2, pos="input")
layer_input.feedforward(x_in=xin_layer_input)
print(layer_input.y)

layer_hidden = neural_layer(w_in=win_layer_hidden, bias=1, n_neurons=3, pos="hidden")
layer_hidden.feedforward(x_in=layer_input.y)
print(layer_hidden.y)

layer_output = neural_layer(w_in=win_layer_output, n_neurons=1, pos="output")
layer_output.feedforward(x_in=layer_hidden.y)
print(layer_output.y)

[1. 0. 0.]
[1.         0.67172558 0.36911857 0.35663485]
[0.33697613]


In [76]:
ann = neural_network(layer_input_neurons=2, layer_hidden_neurons=3, layer_output_neurons=1)

print(ann.w_hidden)
print()
print(ann.w_output)
print("------------------------------------------------")

ann.feedforward(x_in=np.array([0, 0]))
ann.error(target=np.array([0]))
print(ann.layer_input.y)
print()
print(ann.layer_hidden.y)
print()
print(ann.layer_output.y)
print()
print(ann.cost_v)
print(ann.error_epoch)

[[-0.86777734 -0.28844768  0.22927087]
 [ 0.21913913  0.38997344 -0.38146036]
 [ 0.42213292  0.16441958  0.96665243]]

[[-0.62359505]
 [ 0.86521854]
 [-0.23949596]
 [-0.59248539]]
------------------------------------------------
[1. 0. 0.]

[1.         0.295717   0.42838394 0.55706795]

[0.30994294]

[0.09606463]
0.09606462756532115


In [77]:
print(ann.layer_output.w)
print()
ann.backpropagation()
print(ann.layer_output.d)
print()
print()
print()
print(ann.layer_output.d_w)
print()
print(ann.layer_output.w)

[[-0.62359505]
 [ 0.86521854]
 [-0.23949596]
 [-0.59248539]]

[-0.07565422]



[[-0.02269627]
 [-0.00671167]
 [-0.00972272]
 [-0.01264336]]

[[-0.60089878]
 [ 0.87193022]
 [-0.22977325]
 [-0.57984203]]


In [78]:
pass