In [1]:
from MultiLayerPerceptron import *

In [2]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris

In [3]:
xin = np.array([1, 0, 0])
win = np.array([0.716, 0.742, 0.576])
n1 = neural_neuron(w_in=win, layer="hidden", pos=1)
n1.feedforward(x_in=xin)
print(n1.z)

0.671725582405139


In [4]:
print(sigmoid_act(x=0.716, derivate=False))

0.671725582405139


In [5]:
win_layer = np.array([[0.716, -0.536, -0.590],
                      [0.742, -0.262, 0.170],
                      [0.576, 0.872, 0.034]])
xin_layer = np.array([1, 0, 0])
l1 = neural_layer(w_in=win_layer, bias=1 ,n_neurons=3, pos="hidden")
l1.feedforward(x_in=xin_layer)
print(l1.neurons[0].w)
print(l1.neurons[0].pos)
print(l1.y)

[0.716 0.742 0.576]
1
[1.         0.67172558 0.36911857 0.35663485]


In [6]:
xin_layer_input = np.array([0, 0])

win_layer_hidden = np.array([[0.716, -0.536, -0.590],
                             [0.742, -0.262, 0.170],
                             [0.576, 0.872, 0.034]])

win_layer_output = np.array([[-0.754],
                             [-0.590],
                             [0.564],
                             [0.744]])

In [7]:
layer_input = neural_layer(bias=1, n_neurons=2, pos="input")
layer_input.feedforward(x_in=xin_layer_input)
print(layer_input.y)

layer_hidden = neural_layer(w_in=win_layer_hidden, bias=1, n_neurons=3, pos="hidden")
layer_hidden.feedforward(x_in=layer_input.y)
print(layer_hidden.y)

layer_output = neural_layer(w_in=win_layer_output, n_neurons=1, pos="output")
layer_output.feedforward(x_in=layer_hidden.y)
print(layer_output.y)

[1. 0. 0.]
[1.         0.67172558 0.36911857 0.35663485]
[0.33697613]


In [8]:
ann = neural_network(layer_input_neurons=2, layer_hidden_neurons=3, layer_output_neurons=1)
print(ann.w_hidden)
print()
print(ann.w_output)
print("------------------------------------------------")
ann.feedforward(x_in=np.array([0, 0]))
print(ann.layer_input.y)
print()
print(ann.layer_hidden.y)
print()
print(ann.layer_output.y)

[[ 0.28986176 -0.13492661  0.68257632]
 [-0.77752116  0.30510972 -0.67098417]
 [-0.06315737  0.87335075 -0.94743139]]

[[-0.68076704]
 [ 0.64335286]
 [ 0.70829552]
 [-0.20336073]]
------------------------------------------------
[1. 0. 0.]

[1.         0.57196229 0.46631943 0.66431346]

[0.47063464]
